### ISSUE TITLE
`eo:cloud_cover` Discrepancy Between Sentinel-2 L1C and L2A STAC Records

### ISSUE THREAD

**Issue by DanSchoppe** [stac-utils/stac-server#104]
I bumped into a strange issue where the STAC-reported `eo:cloud_cover` values are sometimes wildly different between the Sentinel-2 L1C and L2A collections:
```
$ curl -s 'https://earth-search.aws.element84.com/v0/search' --data-raw '{"ids": ["S2B_18TWN_20210510_0_L1C"],"limit":1}' --compressed | python -m json.tool | grep eo:cloud
                "eo:cloud_cover": 99.86,
```

```
$ curl -s 'https://earth-search.aws.element84.com/v0/search' --data-raw '{"ids": ["S2B_18TWN_20210510_0_L2A"],"limit":1}' --compressed | python -m json.tool | grep eo:cloud
                "eo:cloud_cover": 0,
```

FWIW these rasters are fully cloudy, so in the above example the L1C data is correct and the L2A is not. Given that L2A data is derived from L1C, I imagine this drastic difference is a bug somewhere in the processing pipeline.

@matthewhanson would you imagine that the root cause of this lives in this repo? Or whatever infrastructure is building SNS events? Or perhaps even further upstream in ESA's `sen2cor` tooling?

Thanks!
Dan

**Comment by matthewhanson** [comment]
@DanSchoppe this is a known problem unfortunately.

The issue is that the L2A scenes as published in eu-central-1 (and that are inputs to the COG versions) had a problem with the cloud cover in the original tileInfo.json file in that it was always set to "0".  I worked around this by fetching the L1C data for every L2A scene and getting the cloud cover from that tileInfo.json file.  However, for whatever reason, sometimes the L1C data was not available at the time, so in those cases I set `eo:cloud_cover` to 0, but also set the field `sentinel:valid_cloud_cover` to `false`, as can be seen in your case:
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a/items/S2B_18TWN_20210510_0_L2A

I'm not sure why the L1C tileInfo.json file wasn't available at the time but was then added later, as we see in your case since the L1C file does exist:
https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l1c/items/S2B_18TWN_20210510_0_L1C

I'm currently working on a Earth-Search v1 API that will have updated STAC metadata (and updated API) and will be ingesting all the L1C and L2A data again so hope to improve this.  In the case where there still isn't L1C data available i've come to the conclusion that omitting `eo:cloud_cover` entirely is preferable than providing a 0 and setting another field so will likely do that.

I'm not sure yet what this means for the L2A COGs, I'd like to get those updated and processed in a new pipeline, but I have to figure out logistics on how and when to cut over since there's other systems relying on the v0 API (which won't be going away for a while but I need to figure out a transition plan).

**Comment by DanSchoppe** [comment]
@matthewhanson Thanks so much for the detailed response! It all makes sense. Sorry that the L2A metadata in `eu-central-1` seems to be the root cause and you're dealing with all this fallout 😦

Are the L2A `tileInfo.json` files produced by a public repo? Just wondering if there'd be an opportunity to open this issue there to help raise awareness.

**Comment by DanSchoppe** [comment]
Closing this issue since the root cause seems to be upstream. Let me know if you're aware of an upstream public repo that this issue can be reported in. Thanks @matthewhanson 🙏
