### ISSUE TITLE
Get serverless local working with dockerized Elasticsearch instance

### ISSUE THREAD

**Issue by PeteShepley** [stac-utils/stac-server#11]
Create a docker-compose for elasticsearch.
Make sure local api can see the elasticsearch.

**Comment by matthewhanson** [comment]
@seanmurph You mentioned getting a local instance working for development.  Did you have any instructions for that? Can I use an docker container with elasticsearch for that?

**Comment by seanmurph** [comment]
> @seanmurph You mentioned getting a local instance working for development. Did you have any instructions for that? Can I use an docker container with elasticsearch for that?

I do have some instructions! I'd like to find a way to commit offline support without mudding up the repo. The only part of my support for that I was hesitant to commit was:

<img width="668" alt="Screen Shot 2020-04-22 at 10 22 55 PM" src="https://user-images.githubusercontent.com/3207/80052231-3124dd00-84e8-11ea-8341-f3a5cee964db.png">

When I run offline, it doesn't use the `artifact` line and instead needed the whole path in the handler. I wasn't sure if I commit this it'd break anything.

---

When I ran mine I used an ElasticSearch instance I found deployed inside the dev environment:

```
    ES_HOST: search-sat-api-dev-es6-jrjfioir2m54xolm2oznqhyz54.us-west-2.es.amazonaws.com
```

But you can definitely run one locally as well. I didn't do that because I didn't know how to ingest any data into it.

**Comment by seanmurph** [comment]
The other work I have for offline is similar to our other private components which provides a way to pull a MFA token on app start, cache it to a local session file, and set those credentials with AWS which happens during `connect() {` inside of the `es.js` file.

**Comment by demiurg** [comment]
I think this is safe to close, as we will have other issues for this. There isn't an explicit need to use serverless-offline, also if we go with CDK, using localstack might work for both CDK and sls deployment.
