### ISSUE TITLE
/dev in all api urls

### ISSUE THREAD

**Issue by isaaccorley** [stac-utils/stac-server#277]
Hi,

We setup a STAC server in AWS following the instructions in the README. Everything works fine except that all the urls contain `/dev` in them which is not what other tools like STAC Browser expect. 

E.g. `https://XXX.execute-api.us-west-2.amazonaws.com/dev/search`

Is there a simple fix for this?

@jonlwowski012

**Comment by philvarner** [comment]
Other tools like stac browser take the root URL for the STAC API (e.g., the landing page), which is `https://XXX.execute-api.us-west-2.amazonaws.com/dev/` in this case.

Also, most people usually configure a vanity domain to point to the Gateway API url stage ("dev" in this case), so that doesn't appear in the user-facing url
