### ISSUE TITLE
Migration to OpenSearch Question

### ISSUE THREAD

**Issue by jlaura** [stac-utils/stac-server#441]
@philvarner 

We have a question about the OS migration on AWS. We have completed the following:
    
   1. Updated the existing CF (stac-server-prod) to include DeletionPolicy: Retain and UpdateReplacePoly: Retain under AWS::Elasticsearch::Domain definition.
    2. Manually updated the Elasticsearch domain to OpenSearch in the aws console.
    3. Grabbed the 5.2.0 version code and updated the serverless.yml as suggested (Only updated this locally).
    4. Ran npm run package and grabbed only the OpenSearchInstance from the generated template.
    5. Uploaded the template containing only the OpenSearchInstance by using Create stack and With existing resources (import resources). I used the existing domain name (stac-server-prod-es) and called the new stack stac-server-prod-v5

We are confused by: Switch the DNS entry for the domain name to the API Gateway endpoint for the new Stack. We never pushed a new stack with the other resources because we were waiting for the instruction to say to run `npm deploy` with the new serverless.yml but it never mentioned to do that. Before deleting the old stack, we wanted to see if we did everything right.

When should one run the `npm deploy` on the new stack in the migration instructions?

Thanks!

**Comment by philvarner** [comment]
Ah yes, I seem to have missed adding that. deploy of the new stack should be done right before the "Switch the DNS entry for the domain name to the API Gateway endpoint for the new Stack." 

The main point here is that you're creating the stack with new name manually and importing the existing OpenSearch instance into it, so when you do the serverless deploy, the deploy sees that the OpenSearch instance already exists and doesn't try to create a new one, but does create all of the other resources.

**Comment by amystamile-usgs** [comment]
@philvarner I ran the stack deploy as you suggested and am running into the following error:

`CREATE_FAILED: OpenSearchInstance (AWS::OpenSearchService::Domain)
stac-server-prod-es already exists in stack arn:aws:cloudformation:us-west-2:235348801643:stack/stac-server-prod-v5/9cea14b0-d7f1-11ed-afe8-06d1738aea2b`

The stack creation then runs a rollback and deletes all the other resources it created.

**Comment by philvarner** [comment]
Sorry, the instructions in the README seem to be different than what I ended up doing in my upgrade, and I never updated those.

Here's what I did:

- Add DeletionPolicy setting to Elasticsearch domain won't be deleted when it’s removed from the serverless-generated CF stack
- Deploy with that setting to update Elasticsearch
- Remove the OpenSearch definition from the serverless.yml CF template  to “disconnect” it from the serverless/CF stack and deploy to cause the removal from the CF Stack. From here on, the Elasticsearch/OpenSearch domain will be managed independently from the Stack. This also requires replacing the all of the Refs to the ES definition in the serverless.yml file with the actual deployed values they have (since you can no longer ref the ES/OpenSearch endpoint).
- Upgrade the Elasticsearch domain to OpenSearch 1.3 in compatibility mode and then 2.3 in compatibility mode. Each of these upgrades will take a while. (Phil: in the ES/OS split, Elastic added some special behavior to the server API to intentionally break API-level compatibility between the two APIs. I think this was added after the 7.10 server release and 7.9 client release, but compatibility mode will ensure that it’s not a problem. Also note that we’re using the 7.9 client b/c the 7.10 was not yet out the last time we upgraded it, but most major version combinations are compatible)
- Deploy stac-server 0.5.x and ES_COMPAT_MODE = false and validate it works
- Import the OpenSearch cluster back  into the CloudFormation template: Generate the serverless template with the package command, export the CF template from the existing stack in the AWS Console, add the OpenSearchInstance resource to the CF template, use the AWS Console to import the OpenSearch cluster using that modified template.
- Add the OpenSearch definition back to serverless.yml and deploy. This should be a no-op, as the deployed stack should be the same as the serverless config now.
