### ISSUE TITLE
AWS Architecture

### ISSUE THREAD

**Issue by waseem-aidash** [stac-utils/stac-server#57]
Can someone help me with AWS Architecture which gets deployed by this repo. Thanks

**Comment by geomatician** [comment]
The AWS Services used are OpenSearch (formerly called Elastic Search in AWS), Lambda, SNS, SQS, S3 and API Gateway. 

When you deploy this repo, it creates one or more items in all of these services. Once the repo is deployed, you would need to first publish to an SNS topic, which would then send a message to an SQS queue, which would then trigger the corresponding Lambda ingest function (there is a separate Lambda function if the STAC item was ingested properly and a separate one for if the STAC item was not ingested properly, in which case it would go to a dead-letter queue). The goal of the Lambda ingest function is to ingest the STAC items/collections so that they can be indexed using Open Search. Then, you would have to run the  'create-indices' JSON within the Lambda ingest function to create the indices and mappings in Open Search so that the STAC items and collections can be indexed and searched. 

As this repo uses Serverless, a couple of packages for Serverless are created during deployment, and they are all written to an S3 bucket. 

All the items that are a part of the application are also deployed in a single CloudFormation stack.
