### ISSUE TITLE
Item updates should replace existing item

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/stac-server#76]
When ingesting an already existing item the fields are replaced and added, but fields that are not in the new item are left. 

Investigate the different methods in Elasticsearch to update/add records.

The `created` timestamp should remain the same as the original and `updated` should reflect the update time

**Comment by matthewhanson** [comment]
See this line where item is updated: https://github.com/stac-utils/stac-server/blob/main/libs/esStream.js#L57

**Comment by jkeifer** [comment]
It seems ingest is using the `update` action, whereas `index` might be more along the lines of the desired action (see the `update` docs for more info: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html).

More specifically, the `update` action is for modifying an existing document as a "patch" operation and not a replace. We also use the `doc_as_upsert` option to create a new document if the target does not yet exist. The `update` docs linked above explicitly call out the case of wanting to replace a document as a use-case for the `index` action: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html.

However, using `index` alone does not fulfill the stated requirement to retain the original `created` timestamp. Unfortunately, the only way I see that working is adding the latency of an additional round trip to ES to query for an existing document from which we can pull the original created timestamp. That said, note that the current `update`-based approach also does not retain the original `created` timestamp, as that is included in the in the update `doc`. With the `doc_as_upsert` all fields in `doc` override those on the existing document. We could fulfill the requirement to keep `created` unmodified with `update` by not using `doc_as_upsert`, and instead passing all fields except `created` as part of the `upsert` request field. `created` would be the lone attribute in `doc`, which would not be applied if the record already exists. However, this does not remove fields that are not part of `upsert` or `doc`.

It may also be possible to leverage the `script` field on the request to iterate recursively through the existing document to find all fields that are not in the `upsert` or `doc` objects and delete them, but that would require some experimentation and adds a fair bit of complexity to something that is otherwise handled by `index`.

**Comment by jkeifer** [comment]
I think if #131 makes it in, then it would be fairly straightforward to add an extra bulk query as part of the data prep steps for ingest that we can use to preserve any properties like `created` that should not get overwritten on successive ingests for an item.
