### ISSUE TITLE
Query by collection?

### ISSUE THREAD

**Issue by gjones84** [stac-utils/stac-server#86]
Is there any way I can construct a query to limit search results to a specific collection?

I'm using Earth Search (https://earth-search.aws.element84.com/v0/), and I only want to retrieve results from the sentinel-s2-l1c collection, but I'm also getting sentinel-s2-l2a results, which is resulting in too many records, and appears to be causing CORS errors if I set the limit to more than 916 results.

916 results sounds like a lot, but since there are two L2A results for every L1C result, it effectively means I can't retrieve more than about 300 L1C results from a single search query. In practice this means I can only populate a list of results from today back to March 2019, when I want to see all results back to Jan 2016.

**Comment by matthewhanson** [comment]
Hi @gjones84 sorry for the delay, I was just cleaning up the issues here and saw I never responded to this.

There is a way,  you can use the `collections` parameter in your POST request
```
{
    "collections": ["sentinel-s2-l1c"]
}
```

With Earth-search v0 it doesn't really work with GET requests (this has been fixed in the upcoming v1 of Earth-search which is using stac-server 0.3.0)
