### ISSUE TITLE
Create explicit APIGateway mappings for all endpoints

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/stac-server#92]
Right now

https://github.com/stac-utils/stac-server/blob/main/serverless.yml#L42

which uses `{proxy+}` and ANY, so any request method is supported at all points.

GET should be supported at all endpoints

POST should be supported at `/search`

The transaction extension, when added, will add additional methods at `/collections/<collectionId>/items`

**Comment by matthewhanson** [comment]
Research architecture options and recommend

**Comment by geomatician** [comment]
Here is what needs to be done:

An API Gateway **Route** is composed of a a **Method** (GET, POST, PUT, DELETE, ANY, etc.) and a **Resource** (path on which that method can operate). 

If GET needs to be supported on all endpoints, it should be added as a method that operates on the resource "/".

If POST needs to be supported only on "/search", it should be added as a method only on the resource "/search".

For the transaction extension, since it will add multiple methods at the resource located at  /collections/<collectionId>/items, it should have a method of 'ANY' that allows requests to the resource at /collections/{collectionId}/items. ANY means that multiple methods are supported. The collectionID has curly braces around it so that any collection ID can be provided and it will map to that resource (i.e the items within that collection ID). 

Therefore, the serverless.yml file should look like this in lines 44-52:

    events:
      - http:
          method: GET
          path: "/"
          cors: true
      - http:
          method: POST
          path: "/search"
          cors: true
      - http:
          method: ANY
          path: "/collections/{collectionId}/items"
          cors: true

**Comment by marchuffnagle** [comment]
@matthewhanson Rather than explicit API Gateway endpoints, I think we can achieve the same result by using [Express](https://expressjs.com/) to handle routing. That would give us a lot of other benefits: a documented and tested framework, the ability to more easily run the API locally, the option to host somewhere other than Lambda in the future, easier testing, to name a few.

I've done a quick prototype and migrating the API over only took about 30 minutes. The bigger issue is that the migration revealed a number of issues with the tests that would need to be addressed. I can't imagine that would be real challenging to get sorted out, though.
